# Debugger Model Context Protocol (MCP) Tools
# Generated by SText Agent to provide programmatic access to DAP capabilities.
# Fully refactored to be focus-independent and comprehensive.

import sublime
import sys
import os
import threading
import importlib

# Standard import of sublime-mcp.sublime_mcp to register tools
try:
    sublime_mcp = importlib.import_module("sublime-mcp.sublime_mcp")
    register_mcp_tools = sublime_mcp.register_mcp_tools
    unregister_mcp_tools = sublime_mcp.unregister_mcp_tools
except Exception as e:
    print("[Debugger-MCP] Error importing sublime-mcp:", e)
    register_mcp_tools = lambda tools: None
    unregister_mcp_tools = lambda tools: None

def get_debugger():
    db_mod = sys.modules.get("Debugger.modules.debugger")
    if not db_mod or not hasattr(db_mod, "Debugger"):
        return None
    for dbg in db_mod.Debugger.debuggers_for_window.values():
        if dbg.is_running():
            return dbg
    for dbg in db_mod.Debugger.debuggers_for_window.values():
        if dbg.is_open():
            return dbg
    return db_mod.Debugger.get(sublime.active_window(), create=False)

def mcp_debugger_get_state(body):
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
    
    result = {
        "window_id": dbg.window.id() if hasattr(dbg, "window") else None,
        "is_open": dbg.is_open(),
        "is_running": dbg.is_running(),
        "is_paused": dbg.is_paused(),
        "sessions": []
    }
    
    for session in dbg.sessions:
        active_thread = None
        active_frame = None
        if session.selected_thread:
            active_thread = {
                "id": session.selected_thread.id,
                "name": session.selected_thread.name
            }
        if session.selected_frame:
            active_frame = {
                "id": session.selected_frame.id,
                "name": session.selected_frame.name,
                "file": session.selected_frame.source.path if session.selected_frame.source else None,
                "line": session.selected_frame.line
            }
            
        result["sessions"].append({
            "name": session.name,
            "state": str(session.state),
            "active_thread": active_thread,
            "active_frame": active_frame
        })
        
    return result

def mcp_debugger_get_breakpoints(body):
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    result = {"source_breakpoints": [], "function_breakpoints": []}
    if dbg.breakpoints:
        if dbg.breakpoints.source:
            for bp in dbg.breakpoints.source.breakpoints:
                result["source_breakpoints"].append({
                    "file": bp.file,
                    "line": bp.line,
                    "enabled": bp.enabled,
                    "condition": bp.condition,
                    "log_message": bp.log_message
                })
        if dbg.breakpoints.function:
            for bp in dbg.breakpoints.function.breakpoints:
                result["function_breakpoints"].append({
                    "name": bp.name,
                    "enabled": bp.enabled,
                    "condition": bp.dap.condition if hasattr(bp, "dap") else None
                })
    return result

def mcp_debugger_toggle_breakpoint(body):
    file_path = body["file_path"]
    line = body["line"]
    
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    if dbg.breakpoints and dbg.breakpoints.source:
        dbg.breakpoints.source.toggle_file_line(file_path, line)
        return {"success": True, "message": "Toggled breakpoint on line {} in {}.".format(line, file_path)}
    return {"error": "Breakpoints manager not available."}

def mcp_debugger_clear_breakpoints(body):
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    if dbg.breakpoints:
        dbg.breakpoints.remove_all()
        return {"success": True, "message": "All breakpoints removed."}
    return {"error": "Breakpoints manager not available."}

def mcp_debugger_control(body):
    action = body["action"]
    config_name = body.get("configuration_name")
    
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded or active."}
        
    core = sys.modules.get("Debugger.modules.core")
    if not core:
        return {"error": "Debugger core not loaded."}
        
    def _run_action():
        if action == "start":
            if config_name:
                configs = dbg.project.configurations
                target_config = next((c for c in configs if c.name == config_name), None)
                if target_config:
                    dbg.start(target_config)
                    return {"success": True, "message": "Debugger started with config '{}'.".format(config_name)}
                else:
                    return {"error": "Configuration '{}' not found in project configurations.".format(config_name)}
            else:
                dbg.open()
                return {"success": True, "message": "Debugger view opened."}
        elif action == "stop":
            dbg.stop()
            return {"success": True, "message": "Debugger stopped."}
        elif action == "pause":
            dbg.pause()
            return {"success": True, "message": "Debugger paused."}
        elif action == "resume":
            dbg.resume()
            return {"success": True, "message": "Debugger resumed."}
        elif action == "step_over":
            dbg.step_over()
            return {"success": True, "message": "Step over executed."}
        elif action == "step_in":
            dbg.step_in()
            return {"success": True, "message": "Step in executed."}
        elif action == "step_out":
            dbg.step_out()
            return {"success": True, "message": "Step out executed."}
        else:
            return {"error": "Unknown action: {}".format(action)}
            
    try:
        res = _run_action()
        return res
    except Exception as e:
        return {"error": str(e)}

def mcp_debugger_get_variables(body):
    ref = body.get("variables_reference")
    
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    session = getattr(dbg, "session", None)
    if not session:
        return {"error": "No active debug session found."}
        
    core = sys.modules.get("Debugger.modules.core")
    if not core:
        return {"error": "Debugger core not loaded."}
        
    try:
        if ref is not None:
            coro = session.get_variables(ref)
            variables = core.run(coro)
        else:
            frame = session.selected_frame
            if not frame:
                return {"error": "Debugger is not currently paused on a stack frame."}
                
            core.run(session.refresh_scopes(frame))
            variables = session.variables
            
        result = []
        for var in variables:
            result.append({
                "name": var.name,
                "value": var.value,
                "variables_reference": var.variablesReference,
                "has_children": var.has_children,
                "evaluate_name": var.evaluateName
            })
        return {"variables": result}
    except Exception as e:
        return {"error": str(e)}

def mcp_debugger_evaluate(body):
    expression = body["expression"]
    
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    session = getattr(dbg, "session", None)
    if not session:
        return {"error": "No active debug session found."}
        
    core = sys.modules.get("Debugger.modules.core")
    if not core:
        return {"error": "Debugger core not loaded."}
        
    try:
        coro = session.evaluate_expression(expression, context="repl")
        response = core.run(coro)
        return {
            "result": response.result,
            "variables_reference": response.variablesReference,
            "type": response.type
        }
    except Exception as e:
        return {"error": str(e)}

# NEW FOCUS-INDEPENDENT ADVANCED DEBUGGER EXTENSIONS

def mcp_debugger_get_callstack(body):
    thread_id = body.get("thread_id")
    
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    session = getattr(dbg, "session", None)
    if not session:
        return {"error": "No active debug session found."}
        
    core = sys.modules.get("Debugger.modules.core")
    if not core:
        return {"error": "Debugger core not loaded."}
        
    try:
        result = {"threads": []}
        if thread_id is not None:
            coro = session.stack_trace(thread_id)
            frames = core.run(coro)
            result["threads"].append({
                "thread_id": thread_id,
                "frames": [{
                    "id": f.id,
                    "name": f.name,
                    "file": f.source.path if f.source else None,
                    "line": f.line,
                    "column": f.column
                } for f in frames]
            })
        else:
            # Gather callstack of active threads
            if session.selected_thread:
                coro = session.stack_trace(session.selected_thread.id)
                frames = core.run(coro)
                result["threads"].append({
                    "thread_id": session.selected_thread.id,
                    "name": session.selected_thread.name,
                    "active": True,
                    "frames": [{
                        "id": f.id,
                        "name": f.name,
                        "file": f.source.path if f.source else None,
                        "line": f.line,
                        "column": f.column
                    } for f in frames]
                })
        return result
    except Exception as e:
        return {"error": str(e)}

def mcp_debugger_get_exception_info(body):
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    session = getattr(dbg, "session", None)
    if not session:
        return {"error": "No active debug session found."}
        
    core = sys.modules.get("Debugger.modules.core")
    if not core:
        return {"error": "Debugger core not loaded."}
        
    thread_id = body.get("thread_id")
    if thread_id is None:
        if session.selected_thread:
            thread_id = session.selected_thread.id
        else:
            return {"error": "No thread selected and no thread_id specified."}
            
    try:
        coro = session.exception_info(thread_id)
        info = core.run(coro)
        return {
            "exception_id": info.exceptionId,
            "description": info.description,
            "break_mode": info.breakMode,
            "details": {
                "message": info.details.message if info.details else None,
                "type_name": info.details.typeName if info.details else None,
                "stack_trace": info.details.stackTrace if info.details else None
            } if info.details else None
        }
    except Exception as e:
        return {"error": str(e)}

def mcp_debugger_add_watch_expression(body):
    expression = body["expression"]
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    if dbg.watch:
        dbg.watch.add(expression)
        return {"success": True, "message": "Added watch expression: '{}'.".format(expression)}
    return {"error": "Watch manager not available."}

def mcp_debugger_get_watch_expressions(body):
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    result = {"watch_expressions": []}
    if dbg.watch:
        for expr in dbg.watch.expressions:
            val = None
            if expr.evaluate_response:
                val = {
                    "value": expr.evaluate_response.value,
                    "has_children": expr.evaluate_response.has_children
                }
            result["watch_expressions"].append({
                "expression": expr.value,
                "message": expr.message,
                "evaluation": val
            })
    return result

def mcp_debugger_add_function_breakpoint(body):
    name = body["name"]
    dbg = get_debugger()
    if not dbg:
        return {"error": "Debugger package not loaded."}
        
    if dbg.breakpoints and dbg.breakpoints.function:
        dbg.breakpoints.function.add(name)
        return {"success": True, "message": "Added function breakpoint on '{}'.".format(name)}
    return {"error": "Breakpoints manager not available."}


TOOLS = [
    ("debugger_get_state",
     "Query the active debugger status (open, running, paused) and active session thread/frame information across all windows.",
     {},
     mcp_debugger_get_state),
     
    ("debugger_get_breakpoints",
     "Get a list of all registered source/function breakpoints and exception filters.",
     {},
     mcp_debugger_get_breakpoints),
     
    ("debugger_toggle_breakpoint",
     "Toggle (add/remove) a breakpoint at a specific line in a file.",
     {
         "type": "object",
         "properties": {
             "file_path": {"type": "string", "description": "The absolute path of the file."},
             "line": {"type": "integer", "description": "The 1-based line number."}
         },
         "required": ["file_path", "line"]
     },
     mcp_debugger_toggle_breakpoint),
     
    ("debugger_clear_breakpoints",
     "Remove all registered breakpoints in the workspace.",
     {},
     mcp_debugger_clear_breakpoints),
     
    ("debugger_control",
     "Control the active debugger session (actions: start, stop, pause, resume, step_over, step_in, step_out) focus-independently.",
     {
         "type": "object",
         "properties": {
             "action": {
                 "type": "string", 
                 "enum": ["start", "stop", "pause", "resume", "step_over", "step_in", "step_out"],
                 "description": "The debugging control action to execute."
             },
             "configuration_name": {
                 "type": "string", 
                 "description": "Optional: Launch configuration name (used only with action='start')."
             }
         },
         "required": ["action"]
     },
     mcp_debugger_control),
     
    ("debugger_get_variables",
     "Retrieve variables and their values from the paused stack frame focus-independently.",
     {
         "type": "object",
         "properties": {
             "variables_reference": {
                 "type": "integer", 
                 "description": "Optional: Reference ID of a variable to fetch child fields of."
             }
         }
     },
     mcp_debugger_get_variables),
     
    ("debugger_evaluate",
     "Evaluate an expression in the current context of the paused debug session focus-independently.",
     {
         "type": "object",
         "properties": {
             "expression": {
                 "type": "string", 
                 "description": "The expression/code statement to evaluate."
             }
         },
         "required": ["expression"]
     },
     mcp_debugger_evaluate),
     
    ("debugger_get_callstack",
     "Get the full chronological callstack/stack trace of active or specific threads focus-independently.",
     {
         "type": "object",
         "properties": {
             "thread_id": {"type": "integer", "description": "Optional: The thread ID. If omitted, returns trace of active selected thread."}
         }
     },
     mcp_debugger_get_callstack),
     
    ("debugger_get_exception_info",
     "Query rich diagnosis and message details of any active exceptions/crashes focus-independently.",
     {
         "type": "object",
         "properties": {
             "thread_id": {"type": "integer", "description": "Optional: The thread ID. If omitted, uses active selected thread."}
         }
     },
     mcp_debugger_get_exception_info),
     
    ("debugger_add_watch_expression",
     "Add an expression to watch live values dynamically during debug pauses focus-independently.",
     {
         "type": "object",
         "properties": {
             "expression": {"type": "string", "description": "The string code expression to watch."}
         },
         "required": ["expression"]
     },
     mcp_debugger_add_watch_expression),
     
    ("debugger_get_watch_expressions",
     "Get a list of all active watched expressions and their live evaluated results.",
     {},
     mcp_debugger_get_watch_expressions),
     
    ("debugger_add_function_breakpoint",
     "Set a breakpoint on a function name (breaks execution whenever that function is entered) focus-independently.",
     {
         "type": "object",
         "properties": {
             "name": {"type": "string", "description": "The name of the target function."}
         },
         "required": ["name"]
     },
     mcp_debugger_add_function_breakpoint)
]

def plugin_loaded():
    print("[Debugger-MCP] Loading focus-independent Debugger MCP extension...")
    register_mcp_tools(TOOLS)
    print("[Debugger-MCP] Successfully registered {} focus-independent Debugger MCP tools!".format(len(TOOLS)))

def plugin_unloaded():
    print("[Debugger-MCP] Unloading focus-independent Debugger MCP extension...")
    unregister_mcp_tools(TOOLS)
    print("[Debugger-MCP] Successfully unregistered focus-independent Debugger MCP tools.")
