# LSP Model Context Protocol (MCP) Tools
# Generated by SText Agent to provide programmatic access to LSP capabilities.
# Fully focus-independent and comprehensive.

import sublime
import sys
import os
import threading
import importlib
import urllib.parse

try:
    sublime_mcp = importlib.import_module("sublime-mcp.sublime_mcp")
    register_mcp_tools = sublime_mcp.register_mcp_tools
    unregister_mcp_tools = sublime_mcp.unregister_mcp_tools
except Exception as e:
    print("[LSP-MCP] Error importing sublime-mcp:", e)
    register_mcp_tools = lambda tools: None
    unregister_mcp_tools = lambda tools: None

def find_view_by_file_path(file_path):
    if not file_path:
        return None
    target_path = os.path.abspath(file_path).lower()
    for window in sublime.windows():
        for view in window.views():
            if view.file_name() and os.path.abspath(view.file_name()).lower() == target_path:
                return view
    return None

def get_or_open_view_for_file(file_path):
    view = find_view_by_file_path(file_path)
    if view:
        return view
    window = sublime.active_window() or (sublime.windows()[0] if sublime.windows() else None)
    if not window:
        return None
    return window.open_file(file_path, sublime.TRANSIENT)

def get_active_session_for_view(view, config_name=None):
    if not view:
        return None
    reg = sys.modules.get("LSP.plugin.core.registry")
    if not reg:
        return None
    wm = reg.windows.lookup(view.window() or sublime.active_window())
    if not wm:
        return None
    for session in wm.get_sessions():
        if config_name and session.config.name != config_name:
            continue
        if session.can_handle(view):
            return session
    sessions = wm.get_sessions()
    if sessions:
        return next((s for s in sessions if not config_name or s.config.name == config_name), None)
    return None

def mcp_lsp_get_sessions(body):
    reg = sys.modules.get("LSP.plugin.core.registry")
    if not reg:
        return {"error": "LSP package registry not loaded."}
    result = []
    for window in sublime.windows():
        wm = reg.windows.lookup(window)
        if not wm:
            continue
        for session in wm.get_sessions():
            result.append({
                "window_id": window.id(),
                "name": session.config.name,
                "state": str(session.state),
                "project_path": wm.get_project_path()
            })
    return {"sessions": result}

def mcp_lsp_get_diagnostics(body):
    file_path = body.get("file_path")
    min_severity = body.get("min_severity", 4)
    
    reg = sys.modules.get("LSP.plugin.core.registry")
    if not reg:
        return {"error": "LSP package registry not loaded."}
        
    result = []
    for window in sublime.windows():
        wm = reg.windows.lookup(window)
        if not wm:
            continue
            
        for session in wm.get_sessions():
            diagnostics_storage = getattr(session, "diagnostics", None)
            if not diagnostics_storage:
                continue
                
            for uri, diags_dict in diagnostics_storage._diagnostics.items():
                local_path = uri
                if uri.startswith("file:///"):
                    local_path = uri[8:]
                    local_path = urllib.parse.unquote(local_path)
                    if sys.platform == "win32":
                        local_path = local_path.replace("/", "\\")
                        
                if file_path and os.path.abspath(local_path).lower() != os.path.abspath(file_path).lower():
                    continue
                    
                for identifier, diags in diags_dict.items():
                    for d in diags:
                        severity = d.get("severity", 1)
                        if severity > min_severity:
                            continue
                        result.append({
                            "window_id": window.id(),
                            "file_path": local_path,
                            "session": session.config.name,
                            "provider": str(identifier),
                            "severity": severity,
                            "message": d.get("message"),
                            "range": d.get("range"),
                            "code": d.get("code"),
                            "source": d.get("source", session.config.name)
                        })
    return {"diagnostics": result}

def execute_lsp_request(method, params, file_path=None, config_name=None, timeout=5.0):
    reg = sys.modules.get("LSP.plugin.core.registry")
    if not reg:
        return {"error": "LSP package registry not loaded."}
        
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view:
        return {"error": "No active view found or resolved for the request."}
        
    session = get_active_session_for_view(view, config_name)
    if not session:
        return {"error": "No active LSP session found for the file: {}".format(view.file_name() or "Untitled")}
        
    proto = sys.modules.get("LSP.plugin.core.protocol")
    if not proto:
        return {"error": "LSP protocol module not loaded."}
        
    req = proto.Request(method, params)
    event = threading.Event()
    res_holder = []
    err_holder = []
    
    def on_result(res):
        res_holder.append(res)
        event.set()
        
    def on_error(err):
        err_holder.append(err)
        event.set()
        
    session.send_request_async(req, on_result, on_error)
    if event.wait(timeout):
        if res_holder:
            return {"result": res_holder[0]}
        else:
            return {"error": str(err_holder[0]) if err_holder else "Unknown error"}
    else:
        return {"error": "LSP request timed out after {} seconds.".format(timeout)}

def mcp_lsp_get_symbols(body):
    file_path = body.get("file_path")
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved to fetch symbols."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    res = execute_lsp_request("textDocument/documentSymbol", {"textDocument": {"uri": uri}}, file_path=view.file_name())
    if "error" in res:
        return res
    return {"symbols": res["result"]}

def mcp_lsp_hover(body):
    line = body["line"]
    column = body["column"]
    file_path = body.get("file_path")
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for hover."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "position": {"line": line, "character": column}
    }
    res = execute_lsp_request("textDocument/hover", params, file_path=view.file_name())
    if "error" in res:
        return res
    return {"hover": res["result"]}

def mcp_lsp_goto_definition(body):
    line = body["line"]
    column = body["column"]
    file_path = body.get("file_path")
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for definition."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "position": {"line": line, "character": column}
    }
    res = execute_lsp_request("textDocument/definition", params, file_path=view.file_name())
    if "error" in res:
        return res
    return {"definitions": res["result"]}

def mcp_lsp_find_references(body):
    line = body["line"]
    column = body["column"]
    file_path = body.get("file_path")
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for references."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "position": {"line": line, "character": column},
        "context": {"includeDeclaration": True}
    }
    res = execute_lsp_request("textDocument/references", params, file_path=view.file_name(), timeout=10.0)
    if "error" in res:
        return res
    return {"references": res["result"]}

def mcp_lsp_format_document(body):
    file_path = body.get("file_path")
    if file_path:
        view = find_view_by_file_path(file_path)
        if not view:
            return {"error": "File is not open on screen. Cannot format a closed file via LSP."}
    else:
        window = sublime.active_window()
        view = window.active_view() if window else None
        
    if not view:
        return {"error": "No open file resolved to format."}
        
    view.run_command("lsp_format_document")
    return {"success": True, "message": "Triggered lsp_format_document command for view: {}".format(view.file_name())}

# NEW FOCUS-INDEPENDENT EXTENSIONS

def mcp_lsp_search_workspace_symbols(body):
    query = body["query"]
    # We can query from any open view
    view = None
    for window in sublime.windows():
        if window.views():
            view = window.views()[0]
            break
            
    if not view:
        return {"error": "No open views to attach search symbol query to."}
        
    res = execute_lsp_request("workspace/symbol", {"query": query}, file_path=view.file_name())
    if "error" in res:
        return res
    return {"symbols": res["result"]}

def mcp_lsp_get_code_actions(body):
    file_path = body.get("file_path")
    start_line = body["start_line"]
    start_col = body.get("start_column", 0)
    end_line = body.get("end_line", start_line)
    end_col = body.get("end_column", 100)
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for code actions."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "range": {
            "start": {"line": start_line, "character": start_col},
            "end": {"line": end_line, "character": end_col}
        },
        "context": {"diagnostics": []}
    }
    res = execute_lsp_request("textDocument/codeAction", params, file_path=view.file_name())
    if "error" in res:
        return res
    return {"code_actions": res["result"]}

def mcp_lsp_rename_symbol(body):
    file_path = body.get("file_path")
    line = body["line"]
    column = body["column"]
    new_name = body["new_name"]
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for rename."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "position": {"line": line, "character": column},
        "newName": new_name
    }
    res = execute_lsp_request("textDocument/rename", params, file_path=view.file_name())
    if "error" in res:
        return res
    return {"workspace_edit": res["result"]}

def mcp_lsp_get_implementation(body):
    line = body["line"]
    column = body["column"]
    file_path = body.get("file_path")
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for implementation."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "position": {"line": line, "character": column}
    }
    res = execute_lsp_request("textDocument/implementation", params, file_path=view.file_name())
    if "error" in res:
        return res
    return {"implementations": res["result"]}

def mcp_lsp_get_type_definition(body):
    line = body["line"]
    column = body["column"]
    file_path = body.get("file_path")
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for type definition."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "position": {"line": line, "character": column}
    }
    res = execute_lsp_request("textDocument/typeDefinition", params, file_path=view.file_name())
    if "error" in res:
        return res
    return {"type_definitions": res["result"]}

def mcp_lsp_get_declaration(body):
    line = body["line"]
    column = body["column"]
    file_path = body.get("file_path")
    
    view = None
    if file_path:
        view = get_or_open_view_for_file(file_path)
    else:
        window = sublime.active_window()
        if window:
            view = window.active_view()
            
    if not view or not view.file_name():
        return {"error": "No open file resolved for declaration."}
        
    api = sys.modules.get("LSP.plugin.api")
    if api and hasattr(api, "uri_from_view"):
        uri = api.uri_from_view(view)
    else:
        normalized_path = os.path.abspath(view.file_name()).replace(os.sep, "/")
        if not normalized_path.startswith("/"):
            normalized_path = "/" + normalized_path
        uri = "file://" + urllib.parse.quote(normalized_path)
        
    params = {
        "textDocument": {"uri": uri},
        "position": {"line": line, "character": column}
    }
    res = execute_lsp_request("textDocument/declaration", params, file_path=view.file_name())
    if "error" in res:
        return res
    return {"declarations": res["result"]}


TOOLS = [
    ("lsp_get_sessions",
     "Get all active Language Server Protocol (LSP) sessions and their status in all open windows.",
     {},
     mcp_lsp_get_sessions),
     
    ("lsp_get_diagnostics",
     "Get all active diagnostics (errors, warnings, hints) from all active LSP servers across all windows.",
     {
         "type": "object",
         "properties": {
             "file_path": {"type": "string", "description": "Optional: Filter diagnostics to this specific absolute file path."},
             "min_severity": {"type": "integer", "description": "Optional: Filter by maximum severity level (1=Error, 2=Warning, 3=Info, 4=Hint). Defaults to 4."}
         }
     },
     mcp_lsp_get_diagnostics),
     
    ("lsp_get_symbols",
     "Get all document symbols (functions, classes, etc.) for a specific file via LSP.",
     {
         "type": "object",
         "properties": {
             "file_path": {"type": "string", "description": "Optional: The absolute file path. Defaults to the active file."}
         }
     },
     mcp_lsp_get_symbols),
     
    ("lsp_hover",
     "Retrieve type definition, signatures, and markdown documentation (hover info) at a specific 0-based position in a file.",
     {
         "type": "object",
         "properties": {
             "line": {"type": "integer", "description": "0-based line index."},
             "column": {"type": "integer", "description": "0-based column index (character offset on the line)."},
             "file_path": {"type": "string", "description": "Optional: The absolute file path. Defaults to the active file."}
         },
         "required": ["line", "column"]
     },
     mcp_lsp_hover),
     
    ("lsp_goto_definition",
     "Get the code definition locations (file paths and ranges) for a symbol at a specific 0-based position in a file.",
     {
         "type": "object",
         "properties": {
             "line": {"type": "integer", "description": "0-based line index."},
             "column": {"type": "integer", "description": "0-based column index."},
             "file_path": {"type": "string", "description": "Optional: The absolute file path. Defaults to the active file."}
         },
         "required": ["line", "column"]
     },
     mcp_lsp_goto_definition),
     
    ("lsp_find_references",
     "Find all reference locations (file paths and ranges) for a symbol at a specific 0-based position in a file.",
     {
         "type": "object",
         "properties": {
             "line": {"type": "integer", "description": "0-based line index."},
             "column": {"type": "integer", "description": "0-based column index."},
             "file_path": {"type": "string", "description": "Optional: The absolute file path. Defaults to the active file."}
         },
         "required": ["line", "column"]
     },
     mcp_lsp_find_references),
     
    ("lsp_format_document",
     "Trigger automatic formatting on the document using the active LSP formatter (e.g. black, ruff).",
     {
         "type": "object",
         "properties": {
             "file_path": {"type": "string", "description": "Optional: The absolute path of the file to format. If omitted, formats the active file."}
         }
     },
     mcp_lsp_format_document),
     
    ("lsp_search_workspace_symbols",
     "Search globally for any symbol definition across the entire active workspace/project focus-independently.",
     {
         "type": "object",
         "properties": {
             "query": {"type": "string", "description": "The search query/string for the symbol name."}
         },
         "required": ["query"]
     },
     mcp_lsp_search_workspace_symbols),
     
    ("lsp_get_code_actions",
     "Retrieve context-aware quick-fixes, imports, or refactorings for a specific range of lines focus-independently.",
     {
         "type": "object",
         "properties": {
             "start_line": {"type": "integer", "description": "0-based starting line index."},
             "start_column": {"type": "integer", "description": "Optional 0-based starting character column. Defaults to 0."},
             "end_line": {"type": "integer", "description": "Optional 0-based ending line index. Defaults to start_line."},
             "end_column": {"type": "integer", "description": "Optional 0-based ending character column. Defaults to 100."},
             "file_path": {"type": "string", "description": "Optional: The absolute path of the file. Defaults to active file."}
         },
         "required": ["start_line"]
     },
     mcp_lsp_get_code_actions),
     
    ("lsp_rename_symbol",
     "Calculate a safe, compiler-checked rename operation across all project files for a symbol at a specific coordinate.",
     {
         "type": "object",
         "properties": {
             "line": {"type": "integer", "description": "0-based line index of the target symbol."},
             "column": {"type": "integer", "description": "0-based character column of the target symbol."},
             "new_name": {"type": "string", "description": "The new name to apply to the symbol."},
             "file_path": {"type": "string", "description": "Optional: The absolute path of the file. Defaults to active file."}
         },
         "required": ["line", "column", "new_name"]
     },
     mcp_lsp_rename_symbol),
     
    ("lsp_get_implementation",
     "Find concrete class/method implementations of an interface symbol focus-independently.",
     {
         "type": "object",
         "properties": {
             "line": {"type": "integer", "description": "0-based line index."},
             "column": {"type": "integer", "description": "0-based column index."},
             "file_path": {"type": "string", "description": "Optional: The absolute file path. Defaults to active file."}
         },
         "required": ["line", "column"]
     },
     mcp_lsp_get_implementation),
     
    ("lsp_get_type_definition",
     "Find the exact type/class definition of a symbol focus-independently.",
     {
         "type": "object",
         "properties": {
             "line": {"type": "integer", "description": "0-based line index."},
             "column": {"type": "integer", "description": "0-based column index."},
             "file_path": {"type": "string", "description": "Optional: The absolute file path. Defaults to active file."}
         },
         "required": ["line", "column"]
     },
     mcp_lsp_get_type_definition),
     
    ("lsp_get_declaration",
     "Find where a symbol is declared (often distinct from its instantiation) focus-independently.",
     {
         "type": "object",
         "properties": {
             "line": {"type": "integer", "description": "0-based line index."},
             "column": {"type": "integer", "description": "0-based column index."},
             "file_path": {"type": "string", "description": "Optional: The absolute file path. Defaults to active file."}
         },
         "required": ["line", "column"]
     },
     mcp_lsp_get_declaration)
]

def plugin_loaded():
    print("[LSP-MCP] Loading focus-independent LSP MCP extension...")
    register_mcp_tools(TOOLS)
    print("[LSP-MCP] Successfully registered {} focus-independent LSP MCP tools!".format(len(TOOLS)))

def plugin_unloaded():
    print("[LSP-MCP] Unloading focus-independent LSP MCP extension...")
    unregister_mcp_tools(TOOLS)
    print("[LSP-MCP] Successfully unregistered focus-independent LSP MCP tools.")
